# Generated by Django 4.0 on 2022-11-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipesmodel_difficulty_recipesmodel_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesmodel',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='instruction',
            field=models.ManyToManyField(to='recipes.InstructionModel'),
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='quantity',
            field=models.ManyToManyField(to='recipes.QuantityModel'),
        ),
    ]
